#!/data/data/com.termux/files/usr/bin/python
import platform,os
#####
os.system('xdg-open https://chat.whatsapp.com/Ha7Ef6UDjCrLTxp6p5eAwb')
os.system("git pull")
bit = platform.architecture()[0]
if bit == '64bit':
    import c
elif bit == '32bit':
    print('\033[1;97m[✓] SORRY BRO YOUR DEVIS IS 32 BIT ')
 
