#!/data/data/com.termux/files/usr/bin/python3
# -*- coding: utf-8 -*-

import os
bit = os.uname().machine
os.system('git checkout -- . && git pull')
os.system('chmod 777 *')
if '64' in bit:
    try:
        import c
    except ImportError:
        os.system("pkg update -y && pkg upgrade -y")
        os.system("pkg install git python -y")
else:
    os.system('clear')
    print('>>> TOOL NOT AVAILABLE FOR 32 BIT DEVICE')
